### ISSUE TITLE
Not logged in anymore after page reload

### ISSUE THREAD

**Issue by dmonad** [rwth-acis/openidconnect-signin#1]
This is also an issue with requirements-bazaar. Maybe the access token should be stored in a cookie?

**Comment by istvank** [comment]
Yes, this is a good one. In fact, we are already storing the access_token in localstorage for the popup functionality. We should simply let it there, and check on load, if there is a valid access_token.

**Comment by hugifix** [comment]
In Requirements Bazaar sometimes the log in does not work. 
When I click the sign in button in Firefox the popup opens, but no content will load. In Chrome the popup does open with the content of Requirements Bazaar instead of the log in form.

**Comment by dmonad** [comment]
You should probably open a new issue for that. Unless you think it is related.

**Comment by istvank** [comment]
@dmonad I was just going to write the same... It's definitely a new issue.

**Comment by FBasels** [comment]
I cannot find these problems with the login of the requirements bazaar, so I guess it was fixed a while ago. As far as I know, the req baz will get a new login button at all in its new version, so I close this issue here.
