### ISSUE TITLE
Documentation page isn't opening up

### ISSUE THREAD

**Issue by rmeissn** [rwth-acis/openidconnect-signin#19]
Trying to open https://rwth-acis.github.io/openidconnect-signin/ resolves with: `Could not load descriptor "analysis.json". [object ProgressEvent]`

**Comment by istvank** [comment]
I don't get this log. I tried with both the latest Firefox and Chrome on Mac. When does this occur for you?

**Comment by rmeissn** [comment]
I digged a bit deeper and my Adblocker (uBlock Origin) is blocking your analyse.js file, which causes the website to crash. I guess either my Adblocker shouldn't block the file (cause it's not analysing/tracking me) or your site shouldn't rely on a tracker being present.

**Comment by istvank** [comment]
The issue then seems to be with the ad blocker. We can try to update the iron-component-page to 3.0.1, though to see if the issue persists.

**Comment by rmeissn** [comment]
It still persists. I guess the adblocker blocks the file because of it's name.
