### ISSUE TITLE
Fix OpenID-Connect Button

### ISSUE THREAD

**Issue by Leogomat** [rwth-acis/openidconnect-signin#22]
Right now our nice [openidconnect-button ](https://github.com/rwth-acis/openidconnect-signin) doesn't work as part of the statusbar or in any way when connected to with Chrome. The error message is `Cannot read property Version of undefined`. The reason is probably to a breaking change in the [main dependency](https://github.com/IdentityModel/oidc-client-js).

**Comment by FBasels** [comment]
It was because of some wierd problems with the oidc-client-js package. We have our own fork of it now and the problem here should be fixed with the PR #28.
