### ISSUE TITLE
Update/fix keycloak self-service URL

### ISSUE THREAD

**Issue by slupczynskim** [rwth-acis/openidconnect-signin#29]
The link for "Register an OIDC-token using the [Learning Layers Self-service](https://api.learning-layers.eu/o/oauth2/manage/dev/dynreg)" is outdated.  
Not only is it showing the old domain (api.learning-layers.eu instead of auth.las2peer.org), but also is it 404 even with the new domain.

**Comment by FBasels** [comment]
It was the old link for the client creation section of MitreId. After we have migrated to Keycloak, you can create clients in the account console. Link is updated now.
