### ISSUE TITLE
Add 'client_secret'

### ISSUE THREAD

**Issue by dmonad** [rwth-acis/openidconnect-signin#3]
Github also exepects a `client_secret` header according to https://developer.github.com/v3/oauth/

**Comment by istvank** [comment]
Why is this closed again!? (without looking into the issue. :smile:  )

**Comment by dmonad** [comment]
Also google defines the `client_secret` property. But it also works without.. so I assume it works on github too. I don't really get all this stuff :(  Will try it out soon - and reopen the issue if necessary
