### ISSUE TITLE
Authorization Code

### ISSUE THREAD

**Issue by adabru** [rwth-acis/openidconnect-signin#5]
It would be nice if the Authorization Code Flow would be also supported. [This table](http://openid.net/specs/openid-connect-core-1_0.html#Authentication) states that this is needed to obtain refresh tokens, enabling sessions longer than the lifetime of an access_token.

**Comment by istvank** [comment]
Thanks for your feedback. I am looking into it.

**Comment by FBasels** [comment]
Code flow can now be enabled by setting it in the openidconnect-signin element. There is now an example in the demo folder, that uses code flow ([here](https://github.com/rwth-acis/openidconnect-signin/blob/master/demo/index.html#L57))
